//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BankingProject.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BANKINGPROJECT_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_MSG_WAITING          130
#define IDR_MENU_PHULH1                 131
#define IDD_DIALOG_CONTINUE             134
#define IDR_MENU1                       136
#define IDR_MENU_MAIN                   136
#define IDD_DIALOG_BALANCE_HOME         137
#define IDD_DIALOG1                     139
#define IDD_DIALOG_BALANCE_DETAIL       139
#define IDR_MENU_SANGTH5                141
#define IDC_BUTTON1                     1000
#define IDC_BUTTON_TEST                 1000
#define IDC_WAITING_TEXT                1002
#define IDC_BUTTON2                     1004
#define IDC_BUTTON_BALANCE_HOME_SAVING  1005
#define IDC_BUTTON_BALANCE_HOME_CREDIT  1006
#define IDC_BUTTON_BALANCE_HOME_RETURN_CASH 1007
#define IDC_STATIC_BALANCE_HOME_TEXT_HEADER 1008
#define IDC_BUTTON_BALANCE_HOME_DEFAULT 1009
#define IDC_BUTTON_BALANCE_HOME_DEPOSITS 1010
#define IDC_STATIC_BALANCE_DETAIL_TEXT_HEADER 1011
#define IDC_STATIC_BALANCE_DETAIL_MONEY_TEXT 1012
#define IDC_STATIC_BALANCE_DETAIL_MONEY_VALUE 1013
#define IDC_STATIC_BALANCE_DETAIL_TRANSACTION_FEE_TEXT 1014
#define IDC_STATIC_BALANCE_DETAIL_TRANSACTION_FEE_VALUE 1015
#define IDC_STATIC_BALANCE_DETAIL_VAT_TEXT 1016
#define IDC_STATIC_BALANCE_DETAIL_VAT_VALUE 1017
#define IDC_STATIC_BALANCE_DETAIL_BILL_QUESTION_TEXT 1018
#define IDC_BUTTON_BALANCE_DETAIL_BILL_QUESTION_YES 1019
#define IDC_BUTTON_BALANCE_DETAIL_BILL_QUESTION_NO 1020
#define ID_PHULH1                       32771
#define PHULH1_MENULIST                 32772
#define ID_PHULH1_WAITINGSCR            32773
#define ID_SANGTH5_BALANCE              32774
#define ID_SANGTH5_BALANCEDLG           32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1021
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
